# Generated by Django 4.2.7 on 2024-01-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_location_location_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_popular',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
