# Generated by Django 5.0 on 2024-01-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_location_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='wikipedia_link',
            field=models.URLField(blank=True, default=False, null=True),
        ),
    ]
