# Generated by Django 5.0.1 on 2024-01-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_location_wikipedia_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='wikipedia_link',
        ),
        migrations.AddField(
            model_name='location',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='more_info_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
